name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14', '3.15', '3.15t']
    name: unittest - Python ${{ matrix.python-version }}
    env:
      EXPECTED_PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          allow-prereleases: true

      - name: Build and install wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip wheel --no-deps --wheel-dir dist .
          python -m pip install --no-index --only-binary=:all: --find-links dist codespan-reporting
          python -m pip install pytest

      - name: Test installed native extension
        run: python -m pytest -v
